[project]
name = "labs"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pre-commit>=4.6.0",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.4.0",
    "pytest-cov>=7.1.0",
]

[tool.ruff]
extend-exclude = ["tests/conftest.py"]

[[tool.mypy.overrides]]
module = "tests.conftest"
ignore_errors = true

[[tool.mypy.overrides]]
module = "pytest"
ignore_missing_imports = true

[tool.coverage.run]
source = ["src"]
omit = [
    "src/main.py",
    "src/core/cli/app.py",
    "src/core/cli/helpers.py",
    "src/core/cli/input.py",
    "src/demonstration.py"
]
